### ISSUE TITLE
文件是不是缺失了

### ISSUE THREAD

**Issue by Katou-Kouseki** [huankong233/dujiaoka-theme-huankong#1]
View [huankong.static_pages.home] not found.

看起来像是缺少resources/views/路径中的文件

**Comment by huankong233** [comment]
> View [huankong.static_pages.home] not found.
> 
> 看起来像是缺少resources/views/路径中的文件

是的，上次不小心把模板给删掉了，彻底没了（

**Comment by Katou-Kouseki** [comment]
> > View [huankong.static_pages.home] not found.
> > 看起来像是缺少resources/views/路径中的文件
> 
> 是的，上次不小心把模板给删掉了，彻底没了（

呜呜

**Comment by huankong233** [comment]
> > > View [huankong.static_pages.home] not found.
> > > 看起来像是缺少resources/views/路径中的文件
> > 
> > 
> > 是的，上次不小心把模板给删掉了，彻底没了（
> 
> 呜呜

当时是在 https://github.com/binglog/dujiaoka-bing 上面改了一些bug然后发布上来的，然后忘记把views发布上来了，然后不小心在机子上吧独角卡的容器删掉了，数据也没了 悲
